# Generated by Django 4.2.3 on 2023-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="title",
            field=models.TextField(max_length=40, null=True),
        ),
    ]
